version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task: setup
      - task: build

  setup:
    sources:
      - ./go.mod
    cmds:
      - go mod tidy
      - go mod verify
      - go mod download
  cleanup:
    cmds:
      - rm -rf ./.task ./coverage.out

  build:
    deps: [setup]
    cmds:
      - go build -o ./go/bin/nginx_check
  run:
    deps: [setup]
    cmds:
      - go run ./main.go
